alter table "public"."product_search" drop constraint "product_search_pkey";

drop index if exists "public"."product_search_pkey";

create table "public"."product_snapshot" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "asin" text,
    "final_price" double precision not null
);


alter table "public"."product_snapshot" enable row level security;

alter table "public"."product_search" drop column "created_at";

alter table "public"."product_search" drop column "id";

alter table "public"."product_search" alter column "asin" set not null;

alter table "public"."product_search" alter column "search_id" set not null;

CREATE UNIQUE INDEX product_snapshot_pkey ON public.product_snapshot USING btree (id);

CREATE UNIQUE INDEX product_search_pkey ON public.product_search USING btree (asin, search_id);

alter table "public"."product_snapshot" add constraint "product_snapshot_pkey" PRIMARY KEY using index "product_snapshot_pkey";

alter table "public"."product_search" add constraint "product_search_pkey" PRIMARY KEY using index "product_search_pkey";

alter table "public"."product_snapshot" add constraint "product_snapshot_asin_fkey" FOREIGN KEY (asin) REFERENCES products(asin) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."product_snapshot" validate constraint "product_snapshot_asin_fkey";

grant delete on table "public"."product_snapshot" to "anon";

grant insert on table "public"."product_snapshot" to "anon";

grant references on table "public"."product_snapshot" to "anon";

grant select on table "public"."product_snapshot" to "anon";

grant trigger on table "public"."product_snapshot" to "anon";

grant truncate on table "public"."product_snapshot" to "anon";

grant update on table "public"."product_snapshot" to "anon";

grant delete on table "public"."product_snapshot" to "authenticated";

grant insert on table "public"."product_snapshot" to "authenticated";

grant references on table "public"."product_snapshot" to "authenticated";

grant select on table "public"."product_snapshot" to "authenticated";

grant trigger on table "public"."product_snapshot" to "authenticated";

grant truncate on table "public"."product_snapshot" to "authenticated";

grant update on table "public"."product_snapshot" to "authenticated";

grant delete on table "public"."product_snapshot" to "service_role";

grant insert on table "public"."product_snapshot" to "service_role";

grant references on table "public"."product_snapshot" to "service_role";

grant select on table "public"."product_snapshot" to "service_role";

grant trigger on table "public"."product_snapshot" to "service_role";

grant truncate on table "public"."product_snapshot" to "service_role";

grant update on table "public"."product_snapshot" to "service_role";

CREATE TRIGGER "StartScrapingForNewSearches" AFTER INSERT ON public.searches FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://lyokztgvzshwkrselysa.supabase.co/functions/v1/scrape-start', 'POST', '{"Content-type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5b2t6dGd2enNod2tyc2VseXNhIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcyNzkxNjcyMSwiZXhwIjoyMDQzNDkyNzIxfQ.cf9LXv6kpvW2Crmoy3sLWnOT90f5_guZSdqS97XbCnY"}', '{}', '1000');


